server.port=8081

# Spring Actuator Properties
management.endpoints.web.base-path=/api/diagnostics
management.endpoints.web.exposure.include=info,health,loggers,metrics
management.health.db.enabled=false

# Logging Configuration
logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
logging.level.org.springframework.jdbc.core.JdbcTemplate=ERROR
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=ERROR

# JPA & Hibernate Configuration
## Datasource Connection Details
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mdfa
## Hibernate properties
### The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
### Show or not log every SQL query
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
### Hibernate DDL auto (create, create-drop, update, none): with "none" the schema is managed by Liquibase
spring.jpa.hibernate.ddl-auto=none

# Service specific configuration
## This needs to be injected via K8S for each namespace
### IAM Service
asset.analytics.svc.iam.baseUrl=http://localhost:60052
### Device Mgmt. Service
asset.analytics.svc.devicemgmt.baseUrl=http://localhost:60055

